/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CompareRouteImport } from "./routes/compare"
import { Route as Solar_dictionaryRouteImport } from "./routes/solar_dictionary"
import { Route as Solar_systemRouteImport } from "./routes/solar_system"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: "/compare",
  path: "/compare",
  getParentRoute: () => rootRouteImport,
} as any)
const Solar_dictionaryRoute = Solar_dictionaryRouteImport.update({
  id: "/solar_dictionary",
  path: "/solar_dictionary",
  getParentRoute: () => rootRouteImport,
} as any)
const Solar_systemRoute = Solar_systemRouteImport.update({
  id: "/solar_system",
  path: "/solar_system",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/solar_dictionary": typeof Solar_dictionaryRoute
  "/solar_system": typeof Solar_systemRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/solar_dictionary": typeof Solar_dictionaryRoute
  "/solar_system": typeof Solar_systemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/solar_dictionary": typeof Solar_dictionaryRoute
  "/solar_system": typeof Solar_systemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/compare" | "/solar_dictionary" | "/solar_system"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/compare" | "/solar_dictionary" | "/solar_system"
  id: "__root__" | "/" | "/compare" | "/solar_dictionary" | "/solar_system"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  Solar_dictionaryRoute: typeof Solar_dictionaryRoute
  Solar_systemRoute: typeof Solar_systemRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/compare": {
      id: "/compare"
      path: "/compare"
      fullPath: "/compare"
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/solar_dictionary": {
      id: "/solar_dictionary"
      path: "/solar_dictionary"
      fullPath: "/solar_dictionary"
      preLoaderRoute: typeof Solar_dictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/solar_system": {
      id: "/solar_system"
      path: "/solar_system"
      fullPath: "/solar_system"
      preLoaderRoute: typeof Solar_systemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  Solar_dictionaryRoute: Solar_dictionaryRoute,
  Solar_systemRoute: Solar_systemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
